### ISSUE TITLE
Opening the App

### ISSUE THREAD

**Issue by iLikeBamboo** [FTBTeam/FTB-App-Feedback#101]
### What Operating System

Windows 10

### App Version

202111101147-418dcf2f3b-release

### UI Version

418dcf2f3b

### Debug Code

FTB-DBGROLOXOXOJI

### Describe the bug

When I open the app, it shows me "this is a bit awkward", and shows me two things to click: report issue or quit. After a moment, it disappears.

### Steps to reproduce

Open the app.
The end.

### Expected behaviour

I don't know what to write here. I just don't want it to appear.

### Screenshots

![image](https://user-images.githubusercontent.com/95427451/144443655-44702501-a733-4906-8dad-9afbe0c849a2.png)

**Comment by AffrantoMeow** [comment]
I had this and I had it resolved by redownloading Overwolf, see if this helps.

**Comment by MichaelHillcox** [comment]
Added to main list of launch issues #119 thanks for your help by reporting your issue, we're looking into it :+1:
