### ISSUE TITLE
FTB App Modpack Launcher

### ISSUE THREAD

**Issue by Kuktar** [FTBTeam/FTB-App-Feedback#105]
### What version of the app is the feature intended for?

Windows

### What is your feature request?

I would like the option to disable the launcher and laucherprograss .jars. 

Whenever I try and remove them from the modpack (oceanblock) the FTB app will automatically restore/recover/reinstall them. I click the load in-game button but sometimes when the modpack loads the java/minecraft instance is not able to come to the foreground. It will be in the taskbar but invisible. 

Even without that happening, I would love to have the option to disable the launcher. Thanks. 

### Does your request solve an issue?

maybe

### Describe alternatives you've considered

classic minecraft lauancher like MCLauncher and even the normal curse app seem to work just fine without the launcher mod.

### Additional information

thanks for all you do. Oceanblock is awesome.

**Comment by MichaelHillcox** [comment]
This will not be happing, we use this mod to provide better feedback on loading for older modpacks as well as providing a performance improvement for slower machines. We hope to have the mod on all modpacks soon so it'll be a unified experience.
