### ISSUE TITLE
can't launch any game

### ISSUE THREAD

**Issue by InfernousDonuts55** [FTBTeam/FTB-App-Feedback#106]
### What Operating System

MacOS (Latest)

### App Version

202111051727-fc8797cf31-release

### UI Version

fc8797cf31

### Debug Code

fob-debug-macos

### Describe the bug

when laugh the game instantly crash code 0 

### Steps to reproduce

juste launch the game (ocean block)

### Expected behaviour

just launch the game whiteout problem 

### Screenshots

![Capture d’écran 2021-12-09 à 19 45 49](https://user-images.githubusercontent.com/95876481/145457203-29d1afcd-f2fe-4213-80a3-8c7804df5ae3.png)
![Capture d’écran 2021-12-09 à 19 47 58](https://user-images.githubusercontent.com/95876481/145457243-c3c22ab3-818a-4845-9c2c-b1edb08c99bb.png)
[

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
