### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by BraddahJones** [FTBTeam/FTB-App-Feedback#107]
### What Operating System

Windows 10

### App Version

latest version, cant open app to get specific information I did a fresh install on December 9th

### Debug Code

FTB-DBGCUWULACEWI

### Describe the bug

App doesn't launch at all, I get the "preparing for first launch" then it disappears 

### Steps to reproduce

1. Attempt to open FTB App from desktop

### Expected behaviour

After I attempt to open the app, I expect it to open. 

### Additional information

I have tried updating my Windows. Doing a fresh install of the app. Even going back top old forums and trying solutions for previous versions of the Overwolf Launcher, and nothing has worked. I did not install any new software or programs that may be conflicting with the FTB app. One day I tried to open it so and it never launched.

**Comment by MichaelHillcox** [comment]
Added to main list of launch issues #119 thanks for your help by reporting your issue, we're looking into it :+1:
