### ISSUE TITLE
Instance Cannot Update

### ISSUE THREAD

**Issue by frawst123** [FTBTeam/FTB-App-Feedback#108]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

 FTB-DBGAGIBIQUMAS

### Describe the bug

There is a new update for oceanblock and when i go to update the instance it shows all the mods and files and everything but nothing happens afterword's. I've waited 2 hours for it to update

### Steps to reproduce

1. Open the app
2. Oceanblock Instance says Update is available\
3. Click On Oceanblock
4. Click On update Available
5. This is were the problem occurs

### Expected behaviour

The oceanblock instance is supposed to install/update to the newest version available. As an update was available from the version i was previously playing on. 1.9.0 to 1.10.1 beta

### Screenshots

![Update Failed](https://user-images.githubusercontent.com/95933298/145616731-7d73c75f-61b4-4492-b7f2-d1c4359291b6.PNG)

**Comment by boesshawn** [comment]
I'm having the same issue currently.  I uninstalled overwolf, ftb app, then reinstalled. 
It appears to hang at the creating environment step.

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
