### ISSUE TITLE
FTB Ultimate Anniversary Edition modpack installation gets stuck at 99.98% and did not appear to finish installation.

### ISSUE THREAD

**Issue by BrickVoid** [FTBTeam/FTB-App-Feedback#109]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

FTB-DBGKITEPOQUGA

### Describe the bug

I installed the FTB Ultimate Anniversary Edition but the install process was stuck at 99.98% complete and did not appear to finish installing.

### Steps to reproduce

Opened App.
Chose to install FTB Ultimate Anniversary Edition.
Modpack files downloaded.
Installation phase began.
Waited several minutes.
Came back to find FTB Ultimate Anniversary installation was still showing as being 99.98% complete.
Got frustrated with app being unresponsive after several more minutes of waiting.
Rebooted PC.
Reloaded App.
Noticed that FTB Ultimate Anniversary Edition appeared in modpack list after reboot.
Removed modpack, as installation was not shown to be completed properly.

### Expected behaviour

I expected the FTB App to properly complete the modpack installation and provide progress reports on mod installation visible on screen.

### Additional information

I am dismayed at the way in which the FTB App has failed to provide a proper update of what is being installed and when and where.

FIX THIS NOW!

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
