### ISSUE TITLE
ftb app doesn't start

### ISSUE THREAD

**Issue by VanCHous7890** [FTBTeam/FTB-App-Feedback#110]
### What Operating System

Windows 10

### Debug Code

FTB-DBGSEVEHAGEMI

### Describe the bug

the application runs but does not start, hangs at the loading stage, the logo flickers, the download slider moves, but nothing happens, I tried to reinstall it, it did not help

### Steps to reproduce

запуск приложения 

### Expected behaviour

the application runs but does not start, the logo flickers, the download slider moves, but nothing happens, I tried to reinstall it, it didn’t help

### Screenshots

![image](https://user-images.githubusercontent.com/96058801/145812549-50a1b0ad-e015-4505-acb1-1ecb2eb6e7cd.png)

**Comment by MichaelHillcox** [comment]
Added to main list of launch issues #119 thanks for your help by reporting your issue, we're looking into it :+1:
