### ISSUE TITLE
no modded versions of minecraft pop up when i launch a modpack

### ISSUE THREAD

**Issue by CrimsonFlame2001** [FTBTeam/FTB-App-Feedback#112]
### What Operating System

Windows 10

### Debug Code

FTB-DBGANEMATIWOF

### Describe the bug

when i try to launch a modpack (any modpack) it only shows the non-modded minecraft version

### Steps to reproduce

yesterday i closed Ocean Block and when i later wannted to play again it would keep freezing up. when i tried to exit and relaunch the modpack it would tell me the game was already running in the background. if i ignored the problem and try to start it up anyways it would freeze up so i decided to re download the modpack so i clicked ''delete'', this didnt delete the modpack from my computer so i went into the folder where it was stored and deleted it, after i opend my minecraft and saw the modded version still between my installations so i deleted it their aswell. now when i try to download the modpack again it shows up in my ftb app but after i launch the modpack only the non-modded version of minecraft shows up between the installations. 

### Expected behaviour

when i click ''play'' in the ftb app to open a modpack i expect it to launce a modded version of minecraft

### Additional information

i dont know how to find the log files but if you guys need any extra information please let me know.

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
