### ISSUE TITLE
FTB Launches OceanBlock Only

### ISSUE THREAD

**Issue by spicylips** [FTBTeam/FTB-App-Feedback#114]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

FTB-DBGTEVOISQIRA

### Describe the bug

bug is incorrect loading of modpack instance

### Steps to reproduce

1. Open FTB Launcher
2. Load any modpack
3. Notice Minecraft Launcher only loads OceanBlock Instance
4. Press Play
5. Wait through modpack preparation
6. Crash right before loading

### Expected behaviour

Launched Modpack contains the correct instance; completes load

### Additional information

debug code crashes instantly

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
