### ISSUE TITLE
[Bug] Clicking Play Doesn't Load Launcher, Nothing Happens

### ISSUE THREAD

**Issue by Seahpo** [FTBTeam/FTB-App-Feedback#121]
### What Operating System

MacOS (Old)

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

FTB-DBGcannot open keyboard because program is busycipher: NewGCM requires 128-bit block ciphercrypto/sha256: invalid hash state identifiercrypto/sha512: invalid hash state identifiercrypto/x509: domain %d, certificate #%d: %v     (seems broken as well)

### Describe the bug

I click "Play" on a modpack, it shows "Loading" for a few seconds, then goes back to Play and nothing happens. Doesn't boot the launcher like it should

### Steps to reproduce

1. Click "Play" on any installed modpack
2. Nothing happens

### Expected behaviour

Should launch the Minecraft Launcher

### Additional information

Running MacOS Mojave, 10.14.6. I've had no issues with this previously, and I loaded up Revelation totally fine two days ago and many times prior. I tried re-installing the FTBapp, same issue. Nothing else running in background.

My microsoft account got locked for "suspicious activity" for some reason this morning / yesterday, which may have caused this somehow? But I went into the vanilla launcher, unlocked my account (and there was no suspicious activity at all, thanks microsoft), loaded up vanilla 1.18 totally fine, went back to FTBapp and still had the same issue. I unlocked the account before reinstalling the FTBapp as well. I then installed a new modpack (Direwold 1.16), it installed with no problems, yet I still have the same issue when trying to play the modpack. 

Would've posted this in one of the more specific bug threads but they were locked so I'm posting it here, sorry if this isn't really the right spot for it

**Comment by Gr8Knight4u** [comment]
FTB-DBGKAXOCENULI

**Comment by berkay173** [comment]
FTB-DBGURAPUFUZUY

**Comment by Seahpo** [comment]
After messing around with it more I've got a temporary fix. Restarting my computer will fix the bug and opens the launcher, sometimes. The first time I restarted and successfully booted Revelation I quit out of Minecraft and the FTBapp, and then any subsequent attempts didn't work and I got the same bug I made the thread for. Restarted again, successfully loaded Revelation again, then quit out of it but kept the FTBapp open, and then I could load the modpack again. Quit out of the FTBapp and successfully loaded the pack again. 

So restarting seems to fix it, but it doesn't seem to be permanent and there's still some weirdness going on with the FTBapp

**Comment by Redstar123HD** [comment]
FTB-DBGFUYUGIGUXI

**Comment by persona-unknown-glitch** [comment]
FTB-DBGMUTUJATUTE

**Comment by MichaelHillcox** [comment]
This typically only happens when a different Mincraft Launcher is already open. Please ensure there is no other Minecraft Launcher running on the background before pressing play

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install, pack launch system, and we no longer use the Minecraft Launcher. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: `bdf8bdbaca`, subprocess: `202112101445-bdf8bdbaca-release`.
