### ISSUE TITLE
App is stuck

### ISSUE THREAD

**Issue by Terster17** [FTBTeam/FTB-App-Feedback#122]
### What Operating System

Windows 11

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

 FTB-DBGHARIPUSUJA

### Describe the bug

I press the play button but it's 'Smooth font core'  It's stuck in the same place.And the installation screen does not continue in any way.

### Steps to reproduce

1.open the FTB App
2.click StoneBlock 2 playing button
3.Opening Loading screen 
4.Loading is "Smooth Font Core" stuck in here

### Expected behaviour

Opening the game normally

### Screenshots

![Ekran görüntüsü 2022-01-07 222103](https://user-images.githubusercontent.com/65609865/148597627-28bd3f15-2349-4a67-bd34-448e6e3324b2.png)

**Comment by MichaelHillcox** [comment]
This should be fixed in the latest release
