### ISSUE TITLE
Modpack Install Task failed for 1.18 modpack

### ISSUE THREAD

**Issue by Raidobw2** [FTBTeam/FTB-App-Feedback#124]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Log Files

The important one:
https://paste.feed-the-beast.com/view/c617d158

### Debug Code

FTB-DBGRAQEQEREHA

### Describe the bug

NPE on Install Task

### Steps to reproduce

1. Navigate to browse
2. Click CurseForge packs
3. Search "create"
4. Scroll down a bit and click "Create on a potato"
5. Install the modpack
6. Check the NPE happen on the Install Task

### Expected behaviour

The modpack should install or not get stuck on "creating environment" (display an error message)

### Screenshots

![create_on_a_potato](https://user-images.githubusercontent.com/17010632/148673460-891ca0e9-a879-4ad9-ab8c-2b4697b19225.gif)

### Additional information

This was reported in the Discord by a user who waited 10 mins on that download page, and they retried multiple times.
Pack is on MC 1.18 for Forge.
Thanks in advance!

**Comment by BooBooFastCat** [comment]
I have a similar issue with 1.12 modpacks

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install and launch system. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: `bdf8bdbaca`, subprocess: `202112101445-bdf8bdbaca-release`.
