### ISSUE TITLE
bug:unconfirmed

### ISSUE THREAD

**Issue by Nuddl3z** [FTBTeam/FTB-App-Feedback#126]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

FTB-DBGPAHEVILIZE

### Describe the bug

starting the launcher doesnt work at all

### Steps to reproduce

why would u want to reproduce an issue?

### Expected behaviour

should start

### Screenshots

![image](https://user-images.githubusercontent.com/65922531/149248008-420491fc-7c62-447f-a88c-abe454e7504d.png)
https://gyazo.com/5cb96b4ef478f2cb3f6c23793a1c4ac3

### Additional information

please fix this so i can play with my friends

**Comment by MichaelHillcox** [comment]
Restart / Reinstall, see if that fixes it, if not, please re-open the issue
