### ISSUE TITLE
FTB Sky Oddyssey: Not being able to progress

### ISSUE THREAD

**Issue by AvyPL** [FTBTeam/FTB-App-Feedback#128]
### What Operating System

Windows 10

### App Version

1.3.0

### Debug Code

FTB-DBGPEDAWECEGU

### Describe the bug

You can't really progress when you try to place/use some of TechReborn machines that are required to finish the ModPack, the world crashes and you cant join it again anymore.

### Steps to reproduce

1. Craft any TechReborn machine (most of them are crashing the world)
2. Place it
3. Boom, world crashed

### Expected behaviour

Update listed mods: TechReborn, RebornCore

### Additional information

When i updated mods myself i was able to play, but most of people doesnt know how to do it and it would be a lot better for you to just update the modpack

**Comment by MichaelHillcox** [comment]
Modpack / mod issue, not app issue. Please report it to our modpack issue tracker
