### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by oscarusu** [FTBTeam/FTB-App-Feedback#129]
### What Operating System

Windows 11

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

FTB-DBGUNEZEWORID

### Describe the bug

I can't attach any file due to the bug happened on my friend's world , opened in LAN , i cannot connect again , after using a remote modular acces on a modular acces by right clicking while pressing the left mayus button. Minecraft crashes and closes the app.

### Steps to reproduce

1.Get a modular storage on creative. 
2.Get the modular remote access upgrade.
3.Equip it by opening its inventory and right clicking while pressing mayus.

### Expected behaviour

I thought i could keep playing , but now im not able anymore.

**Comment by MichaelHillcox** [comment]
Mod issue, not app issue.
