### ISSUE TITLE
Cannot "open" certain mod packs on the App

### ISSUE THREAD

**Issue by MajorCooke** [FTBTeam/FTB-App-Feedback#131]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Log Files

[latest.log](https://github.com/FTBTeam/FTB-App-Feedback/files/7909735/latest.log)

### Debug Code

FTB-DBGASARUDOZUS

### Describe the bug

Cannot "open" certain mod packs on launcher

### Steps to reproduce

For me, it's just clicking on any modpack icon that I have installed, except for one: FTB Oceanblock.

When it happens, the image below (after click) is all I'm greeted with. No options whatsoever. It's something to do with the `[net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler]: ` error.

### Expected behaviour

To show me the options of the modpack.

### Screenshots

[Before clicking](https://puu.sh/IDX56/bae6c1e0ae.png)
[After clicking](https://puu.sh/IDX2h/f10dc81c46.png)

No options.

### Additional information

There's problems with the instance.json files, I've no idea what happened to those.

Also I tested this over my other laptop - it's not a question of RAM or anything, I just think FTB app could have corrupted some of my installations.

**Comment by MajorCooke** [comment]
Update: Tried it with installing a fresh new modpack, FTB Ultimate. Same result. On both computers.

**Comment by MichaelHillcox** [comment]
We've shipped an update that should address this, If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: `bdf8bdbaca`, subprocess: `202112101445-bdf8bdbaca-release`.
