### ISSUE TITLE
Corrupted/Incomplete Modpacks

### ISSUE THREAD

**Issue by JosEffigy** [FTBTeam/FTB-App-Feedback#132]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

FTB-DBGSAROROBIDE

### Describe the bug

Downloading modpack includes all files and no issues

### Steps to reproduce

(Try to simulate unstable internet)
Select a modpack, download it.
Progress goes slow but instantly completes.
Check mod files: over half of them are 0kb (possibly more than just the mods)

### Expected behaviour

modpack should be working 100% after finishing download

### Additional information

When downloading on unstable connections there is no way to detect whether the modpack is complete or not. Despite not being complete, It gives me the feedback that it is done installing. I have over half the mods at 0KB and there is no way to download only those specific corrupted downloads. 

Fixing the download system to not drop a download and wait for retransmits or retries should fix it, or an integrity check will also do. The download threads arent all that efficient even at 12 threads.

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install and launch system. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: `bdf8bdbaca`, subprocess: `202112101445-bdf8bdbaca-release`.
