### ISSUE TITLE
Stuck on "Creating environment..." when trying to update modpack

### ISSUE THREAD

**Issue by cristian-ig** [FTBTeam/FTB-App-Feedback#133]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Debug Code

FTB-DBGIRONEKOQUZ

### Describe the bug

Stuck on "Creating environment..." when trying to update modpack, FTB Presents Direwolf20 1.16. Updating from 1.13.0 to 1.13.2

### Steps to reproduce

1. Go to Home
2. Click FTB Presents Direwolf20 1.16 modpack
3. Click Update available
4. Gets stuck on "Creating environment..."

### Expected behaviour

Modpack updated

### Screenshots

![image](https://user-images.githubusercontent.com/22623940/150945800-c0a34db4-31df-485d-be84-83a58ff4f512.png)

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install and launch system. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: `bdf8bdbaca`, subprocess: `202112101445-bdf8bdbaca-release`.
