### ISSUE TITLE
Having a issue

### ISSUE THREAD

**Issue by slingring** [FTBTeam/FTB-App-Feedback#134]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Log Files

https://pste.ch/xejayoxiqo
https://pste.ch/afuqomuyoy

### Debug Code

FTB-DBGXAVEHEDORE

### Describe the bug

I cannot load my modpacks in the UI. I have stoneblock 2 and sky odyessey.

### Steps to reproduce

You cant.

### Expected behaviour

me being able to play/load my modpacks

### Screenshots

https://i.imgur.com/vN97QVd.png

### Additional information

Unban me from the discord why am i banned? 
Slingring#9220

**Comment by MichaelHillcox** [comment]
Restart the app, we've fixed this in dev... it'll be released soon
