### ISSUE TITLE
[BUG]: Exit code 0 everytime i launch a modpack 

### ISSUE THREAD

**Issue by Impre-visible** [FTBTeam/FTB-App-Feedback#135]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Log Files

https://pste.ch/imiweheped

### Debug Code

FTB-DBGOCEXAMINIB

### Describe the bug

Exit code 0 everytime

### Steps to reproduce

1. Go to FTB App
2. Install or lauch a mod pack
3. In Minecraft press "PLAY"
4. See the bug

### Expected behaviour

I just want to launch the game to be able to play

### Screenshots

its in french sorry
![image](https://user-images.githubusercontent.com/69050895/151522049-463bea0b-57f9-4cd7-9fb5-28afbd709860.png)

**Comment by MichaelHillcox** [comment]
Looks like the install might not have completed. We have a main list and are currently working on these issues, please try and reinstall :+1: if that doens't fix your issue, please re-open this issue.

**Comment by Impre-visible** [comment]
i already re-installed the app

**Comment by Impre-visible** [comment]
its the third time

**Comment by MichaelHillcox** [comment]
You can run the ftb-dbg too?

**Comment by Impre-visible** [comment]
ftb-dbg ?

**Comment by Impre-visible** [comment]
debug ? yes i send u the infos

**Comment by Impre-visible** [comment]
https://pastebin.com/5CRaT06K

**Comment by Impre-visible** [comment]
can someone help me pls

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install and launch system. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: `bdf8bdbaca`, subprocess: `202112101445-bdf8bdbaca-release`.
