### ISSUE TITLE
Creating Environment... Stoneblock 2

### ISSUE THREAD

**Issue by bpblog** [FTBTeam/FTB-App-Feedback#136]
### What Operating System

Windows 10

### App Version

202112101445-bdf8bdbaca-release

### UI Version

bdf8bdbaca

### Log Files

https://pste.ch/yimiciluli

### Debug Code

FTB-DBGMUYENODUVA

### Describe the bug

The mod pack never finishes downloading, it stays in the step that you see in the image permanently 

### Steps to reproduce

1. Open App
2. click on browse
3. search Stoneblock
4. clic on get

### Expected behaviour

I expected the mod pack to be installed 

### Screenshots

![Sin título](https://user-images.githubusercontent.com/66920718/151706297-912f63a9-08d8-466f-bb81-e1e78c7413ec.jpg)

**Comment by MichaelHillcox** [comment]
We have begun shipping a new version of the app with a completely rewritten install and launch system. If your issue is still happening, please create a new issue once you have tested against the new version. Any version after (ui: `bdf8bdbaca`, subprocess: `202112101445-bdf8bdbaca-release`.
