### ISSUE TITLE
Updating a modpack doesn't show it as updating under My Modpacks

### ISSUE THREAD

**Issue by AKTheKnight** [FTBTeam/FTB-App-Feedback#15]
Clicking update on FTB Omnia didn't show it as Updating under My Modpacks. It just looked normal while at the bottom Forge was being downloaded

**Comment by MichaelHillcox** [comment]
This shouldn't have happened... You shouldn't have been able to see modpacks whilst it was updating. As this is such an old issue. I'll close it for now, please let me know if this still happens.
