### ISSUE TITLE
Update button on the instance card

### ISSUE THREAD

**Issue by Naxanria** [FTBTeam/FTB-App-Feedback#18]
**Is your feature request related to a problem? Please describe.**
When an update is available you get a nice yellow bar with 'update available' (this is awesome).
But when you mouse over you only have the play and instance settings buttons. 

**Describe the solution you'd like**
Would be nice, in case of an update, to have an update button that immediately updates it.

**Additional context**
App version: 1.0.6

**Comment by MichaelHillcox** [comment]
This has kind of been resolved but I don't plan on having a update button on the pack card itself yet. Closing for now but I'll keep it in mind
