### ISSUE TITLE
Janky behavior when hovering over Play/More buttons on modpack card

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-App-Feedback#23]
**Operating System:**
OS: W10

**Installer Version:**
Installer: FTBA_windows-x64_202007042254-9878310b16-develop

![image](https://user-images.githubusercontent.com/15698722/86527317-790a9d80-be63-11ea-9843-3f41baf0c918.png)
Can't figure out how to copy these and I'd rather not manually transcribe

**Log Files:**
https://pste.ch/abanipitit

**Describe the bug**
![ezgif-6-5feff59574b6](https://user-images.githubusercontent.com/15698722/86527331-99d2f300-be63-11ea-9fd8-d3f6465a533d.gif)

**To Reproduce**
1. Move your mouse around the play/more buttons

**Comment by MichaelHillcox** [comment]
Fixed in production
