### ISSUE TITLE
`Access Denied` instead of jar when downloading 1.16.5-forge-36.2.4.jar

### ISSUE THREAD

**Issue by tecywiz121** [FTBTeam/FTB-App-Feedback#28]
### What Operating System

Linux (Debian)

### App Version

202105051818-5b1f30277f-release

### UI Version

3e720d86

### Log Files

```
Unable to download https://s3.amazonaws.com/Minecraft.Download/versions/1.16.5-forge-36.2.4/1.16.5-forge-36.2.4.jar to /home/user/.ftba/bin/versions/1.16.5-forge-36.2.4/1.16.5-forge-36.2.4.jar
```

If I open `1.16.5-forge-36.2.4.jar` in a text editor, I see:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>B7SD4B08S1Q0SDAT</RequestId><HostId>ek/GWrecYyWzg9nZfRXxiiCS2DII7sO/15K68W4dHiecoRc9XYQ5fdUKNmmk5xvhkIGqkdqUMwo=</HostId></Error>
```

These might not line up exactly with the above, I've tried a couple things:

 Uploaded bin/launcher_profiles.json: https://pste.ch/hisuvutari
 Uploaded bin/settings.json: https://pste.ch/gacefuyiha
 Uploading bin/launcher_log.txt: failed to open file
 Uploaded bin/launcher_cef_log.txt: https://pste.ch/avarupinix
 Uploaded logs/latest.log: https://pste.ch/lewuwohexu
 Uploaded logs/debug.log: https://pste.ch/gapavukuli

### Debug Code

FTB-DBGITOHEPUVOQ

### Describe the bug

`Access Denied` instead of jar when downloading forge

### Steps to reproduce

1. Install FTB App
2. Install the OceanBlock modpack (version 1.1.0)
3. Attempt to launch the modpack.
4. Click "Play" in vanilla launcher.
5. Get download error as above.

### Expected behaviour

OceanBlock mod launches

### Additional information

I've tried copying `1.16.5-forge-36.2.4.jar` from my working Windows installation, but the launcher complains about the same file name in a different path. If I put the same file at the second location, it is deleted while launching.

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
