### ISSUE TITLE
When I download a MOD I cannot open it, it brings the old MC up and not the MOD

### ISSUE THREAD

**Issue by xXYoshisanXx** [FTBTeam/FTB-App-Feedback#29]
### What Operating System

Windows 10

### App Version

202109151742-4dfef257db-feature-fixes

### UI Version

4dfef257db

### Debug Code

 WARNING  instances directory: file/directory does not exist

### Describe the bug

It does not let me open mods specifically stoneblock 2

### Steps to reproduce

click play and it opens launcher and does not open right version 

### Expected behaviour

help me fix it

**Comment by MichaelHillcox** [comment]
Close all Minecraft launchers before pressing play
