### ISSUE TITLE
FTB Modpack Installation stucks at Get Forge Information

### ISSUE THREAD

**Issue by Ratnarok** [FTBTeam/FTB-App-Feedback#31]
### What Operating System

Windows 10

### App Version

Current Release

### UI Version

Newest Version

### Log Files

https://pste.ch/marilepoje

### Debug Code

FTB-DBGTEXUDEBIZI

### Describe the bug

The Download stucks at Get Forge Information when i try to Download any Pack

### Steps to reproduce

1. Launch overwolf
2. Launch FTB
3. Installation of any FTB modpack
4. Download stucks

### Expected behaviour

It should Download the Pack.

### Screenshots

![2021-09-25_16-23-36](https://user-images.githubusercontent.com/1392007/134811842-35f5a091-241d-4772-bdcb-e5c81675697f.png)

### Additional information

I tried to download any pack, but it keeps stuck, I also reinstalled FTB a few Dozen times and also Reinstalled Overwolf, I also tried to install it on an SSD instead of my HDD but nothing works. Would love if anyone has some Ideas to fix it xD

**Comment by MichaelHillcox** [comment]
Closed in preference for #120
