### ISSUE TITLE
Modpacks open MC Launcher then upon hitting play close launcher and do nothing else

### ISSUE THREAD

**Issue by willthisonework** [FTBTeam/FTB-App-Feedback#36]
### What Operating System

Windows 10

### App Version

202109151742-4dfef257db-feature-fixes

### UI Version

4dfef257db

### Debug Code

FTB-DBGTOFOTUWERI

### Describe the bug

Click play on FTB Universtiy 1.16 or FTB Endeavour, MC launcher opens upon clicking play the launcher says preparring then closes and nothing further happens

### Steps to reproduce

1. click play on any modpack (happens on both modpacks i have installed FTB University 1.16 and FTB Endeavour)
2. Minecraft launcher opens
3. Click play on the launcher
4. MC Launcher closes and FTB App does nothing

### Expected behaviour

Expected modpack to open normally

**Comment by MichaelHillcox** [comment]
Try reinstalling the pack if this is still an issue. If it is still an issue and this doesn't work, please open a new issue after running the debug tool (found in discord or on the template for creating a bug report here)
