### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by AKAMANYT** [FTBTeam/FTB-App-Feedback#40]
### What Operating System

Windows 10

### App Version

202109151742-4dfef257db-feature-fixes

### UI Version

4dfef257db

### Debug Code

FTB-DBGHASUWOXEQI

### Describe the bug

when attempting to download ftb Endeavour the download process will not pass "get forge information"

### Steps to reproduce

i dont know how to reproduce this bug

### Expected behaviour

the modpack to download within two hours

### Screenshots

![Uploading image.png…]()

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
