### ISSUE TITLE
nether painting 

### ISSUE THREAD

**Issue by helpinghans99** [FTBTeam/FTB-App-Feedback#41]
### What Operating System

Windows 10

### App Version

1.1.0

### Debug Code

 FTB-DBGIXOXODUYEN

### Describe the bug

nether painting respawning in the over world

### Steps to reproduce

1. place painting go in
2. place over world painting and go back through
3. now nether painting not working

### Expected behaviour

go to the nether

**Comment by MichaelHillcox** [comment]
Please open this in the correct place https://github.com/FTBTeam/FTB-Modpack-Issues

Thanks :+1:
