### ISSUE TITLE
ftb app failed to prepare the minecraft launcher

### ISSUE THREAD

**Issue by wheatonbegone** [FTBTeam/FTB-App-Feedback#44]
### What Operating System

Windows 10

### App Version

202109151742-4dfef257db-feature-fixes

### UI Version

4dfef257db

### Debug Code

FTB-DBGBIJEDAYOME

### Describe the bug

Whenever I download a new modpack it installs but doesn't change the launcher to the new modpack.

### Steps to reproduce

1. Install any modpack
2. go to launch it
3. once the launcher is up the instance is always set to the first modpack I ever installed

### Expected behaviour

whenever I launch any modpack it will only launch ocean block

**Comment by wheatonbegone** [comment]
Update:

I was able to fix by using task manager on all minecraft instances. The I also unistalled the FTB app and then deleted all files of said modpack.

**Comment by MichaelHillcox** [comment]
Yeah, you can't have any version of the Minecraft launcher open, although, I will note that you could have used the mc launchers native way of switching between installations 

![](https://f002.backblazeb2.com/file/image-sharing/s/2021-10/MinecraftLauncher_ZgcbzTxcxS.png)

So this is what I'd say is likely more of a user error & it not being super clear that this can happen and how to resolve it

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
