### ISSUE TITLE
Unable to launch OceanBlock on macOS - Jar download failure

### ISSUE THREAD

**Issue by jmarler** [FTBTeam/FTB-App-Feedback#48]
### What Operating System

MacOS (Beta)

### App Version

202105051818-5b1f30277f-release

### UI Version

3e720d8

### Log Files

Minecraft launcher shows this error on initial launch after installing modpack:

Failed to download file.
Name: 1.2.0.jar
URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.2.0/1.2.0.jar
Filename on disk: 1.2.0.jar
Path: /Users/jmarler/Library/Application Support/.ftba/bin/versions/1.2.0/1.2.0.jar
Exists: File

The contents of the 1.2.0.jar file are:

AccessDeniedAccess Denied72746R6WAC0BZ2EKyFn5/blVlErQn3Taius1Lhb2tUdxn2TgSbyl9H1453MEmIYWQx34OCQIsEJLTxtKA4lqTQh9Za0=%

Subsequent attempts to launch the modpack result in:

Error: Could not find or load main class

Other older modpacks launch without problems.

### Debug Code

FTB-DBGEPAHIBIFEJ

### Describe the bug

Unable to launch OceanBlock on macOS

### Steps to reproduce

1. Launch FTBApp
2. Install OceanBlock 1.2.0
3. Click View Instance
4. Click Play
5. Click Play
6. Observe error
7. Expected behaviour

### Expected behaviour

The game should launch after clicking play

### Additional information

I have deleted launcher_profiles.json and let it be recreated. I have deleted and reinstalled OceanBlocks several times. I have not tried completely deleting the .ftba directory.

Running macOS Monterrey 21A5534d

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
