### ISSUE TITLE
Launcher crashes after or during long computer hibernation

### ISSUE THREAD

**Issue by Thorinwasher** [FTBTeam/FTB-App-Feedback#49]
### What Operating System

Windows 10

### App Version

202109151742-4dfef257db-feature-fixes

### UI Version

4dfef257db

### Log Files

https://pste.ch/dexosiruvu

App crashes, so not sure if this is the right logs.

### Debug Code

FTB-DBGJERATONISI

### Describe the bug

Launcher gives "Whops this is awkward" message. App can not be used after this, and has to be restarted

### Steps to reproduce

1. Have a instance of FTBapp running
2. AFK on your computer for a long while, my computer goes into "hibernation" mode
3. Activate the computer again, app throws bug

### Expected behaviour

Expected behavior is no behavior; nothing should happen

### Additional information

I tried to force the computer into hibernation, but that did not cause any issues. So this issue might not directly link to that....

**Comment by MichaelHillcox** [comment]
Added to main list of launch issues #119 thanks for your help by reporting your issue, we're looking into it :+1:

**Comment by m0lDaViA** [comment]
I can confirm this bug. It happens to me everytime i get my pc out of hibernation mode on W10 and W11.
![grafik](https://user-images.githubusercontent.com/37399229/148057698-62d0850e-8614-442c-8991-a5cc875d6eb1.png)
