### ISSUE TITLE
Update Modpack (OceanBlock)

### ISSUE THREAD

**Issue by CousinVlad27** [FTBTeam/FTB-App-Feedback#50]
### What Operating System

Windows 10

### UI Version

4dfef257db

### Debug Code

FTB-DBGLAGAVAFUWE

### Describe the bug

When the update for the modpack begins, OceanBlock version 1.1.0 to 1.2.0 in this case, the installer brings up the checklist for each piece of the update, but does not move past "generating environment".

### Steps to reproduce

1. Go to the OceanBlock instance in the FTB App library
2. Click update

### Expected behaviour

It should probably create the environment and resume the update, but after 10 minutes it does not

### Screenshots

![Screenshot 2021-10-05 162011](https://user-images.githubusercontent.com/68943688/136115782-225ac5f0-0892-446e-aae0-c5b46483fc98.png)

**Comment by MichaelHillcox** [comment]
When you ran the debug tool, had you already reloaded the app? Your logs do not seem to show any issues happening... Can you also confirm if this persists over app restarts?

**Comment by CousinVlad27** [comment]
Ran the debug tool again, both when trying to update the pack and after restarting the app. While trying to update, it gave me code FTB-DBGTENIKIWAFO. After restarting the app it gave me code FTB-DBGANUVAWANOS. I have restarted the app several times, ran the modpack several times, but have not uninstalled/reinstalled the modpack.

**Comment by CousinVlad27** [comment]
The UI is now version 4bdfd15050, but the update still behaves the same. I did find the app log which seems to report an error being thrown repeatedly when I try to start the update. 

[index.html.32.log](https://github.com/FTBTeam/FTB-App-Feedback/files/7316540/index.html.32.log)

**Comment by CousinVlad27** [comment]
FIXED ISSUE:
The instance that would not update was missing files called version.json and installer.jar. Copied these over from a fresh instance and the modpack updated perfectly.

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
