### ISSUE TITLE
No toggle for the load in app functionality

### ISSUE THREAD

**Issue by ChristopherJTrent** [FTBTeam/FTB-App-Feedback#53]
### What Operating System

Windows 10

### App Version

202110071354-4bdfd15050-release

### UI Version

4bdfd15050

### Log Files

Log not relevant

### Debug Code

FTB-DBGCIHOZOXEBO

### Describe the bug

Launcher hijacks minecraft mod loading process with no toggle

### Steps to reproduce

1) click play on any modpack
2) click play inside the minecraft launcher that was opened when you performed step 1
3) wait a moment
4) note that the minecraft window has closed, and mod loading is happening inside the FTB app
5) search the entire app for a toggle for this behavior
6) find that no such toggle exists

### Expected behaviour

Minecraft mod loading is allowed to proceed unmolested

### Screenshots

1) click play on any modpack
2) click play on minecraft launcher
3) wait
4) see minecraft title screen

### Additional information

I frankly cannot fathom what use there is to having mods load inside the FTB app instead of using the standard forge modloader that people have been using for almost a decade now.

**Comment by ChristopherJTrent** [comment]
> Note: There's a toggle in the loading screen.

This is absolutely false. Or would you care to show me where in the attached screenshot that this toggle is present?
![image](https://user-images.githubusercontent.com/50601711/136673426-e0e94b39-e446-44b7-a268-36290227c78d.png)

**Comment by ThePaul-T** [comment]
"Load in-game"?

**Comment by ChristopherJTrent** [comment]
No, I don't, because I don't want to go elbow-deep into the log files that the app dumps onto my drive because you guys decided you wanted to be cute and add a "feature" that nobody asked for just so you could hoard the optimizations you've created for the mod loader and keep them from finding their way into anyone else's hands.
