### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by JASE1980** [FTBTeam/FTB-App-Feedback#54]
### What Operating System

Windows 10

### App Version

feed the beast infinity evolved 3.1.0

### UI Version

4bdfd15050

### Log Files

[crash-2021-10-10_10.26.04-server.txt](https://github.com/FTBTeam/FTB-App-Feedback/files/7317900/crash-2021-10-10_10.26.04-server.txt)

### Debug Code

FTB-DBGDUXONIFUJI

### Describe the bug

I JUST STARTED THE GAME AND ONLY ABOUT AN HOUR INTO I BUILT THE MINEING WORLD PORTAL AND NO SOONER DID I GO THROUGH IT THE GAME CRASHED 

### Steps to reproduce

1. fix
2. hopefully only have to do once?
3. thx for the help much appreciated

### Expected behaviour

I EXPECTED TO PLAY WITH OUT CRASHES? IT GETS FRUSTRATING

### Additional information

i tried to play the same on curse forge same game and keep getting error of server tick loop im a noob and dont understand all this stuff i just love minecraft and want to enjoy it

**Comment by MichaelHillcox** [comment]
This is a mod issue, please report it to the correct mod author :+1:
