### ISSUE TITLE
FTB App not letting me choose Java version

### ISSUE THREAD

**Issue by Nensec** [FTBTeam/FTB-App-Feedback#59]
### What Operating System

Windows 10

### App Version

202110071354-4bdfd15050-release

### UI Version

4bdfd15050

### Debug Code

FTB-DBGORIGUPOHAD

### Describe the bug

When I choose to select a Java version to be used it will briefly select it, claim it saves the settings then empty itself again

### Steps to reproduce

Go to a modpack instance
Go to settings
Select Java version

### Expected behaviour

Selected Java version to be saved and used

### Screenshots

![2021-10-15_14-57-49](https://user-images.githubusercontent.com/672037/137490510-5729d3ca-3224-43a7-8f36-ce8e666fbd2c.gif)

**Comment by MichaelHillcox** [comment]
Fixed in production :+1:
