### ISSUE TITLE
typeerror: failed to fetch

### ISSUE THREAD

**Issue by nikiveli** [FTBTeam/FTB-App-Feedback#60]
### What Operating System

Windows 10

### App Version

202110071354-4bdfd15050-release

### UI Version

4bdfd15050

### Debug Code

FTB-DBGUNUZAMIPAR

### Describe the bug

the app is not showing anything

### Steps to reproduce

1. Open the app
2. The app is open
3. Go to browse
4. The site shows TypeError: failes to fetch

### Expected behaviour

I just wanted to load a modpack

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/92636511/137590425-ddf24cff-1ce4-4137-a8ba-750ae84cc933.png)

**Comment by Dubims** [comment]
i also have this problem. If you find a solution pls share it with me!

**Comment by MichaelHillcox** [comment]
Hopefully this is already fixed, if you get this issue again, please let me know.
