### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by BigBroDex** [FTBTeam/FTB-App-Feedback#61]
### What Operating System

Windows 10

### App Version

3.50

### Debug Code

FTB-DBGAMUBIZEPIG

### Describe the bug

One off issue

### Steps to reproduce

Reload by Quitting the app using the Quit button or report the issue

### Expected behaviour

Load perfectly

### Screenshots

![image](https://user-images.githubusercontent.com/87274428/137596990-80c962de-8564-4395-86c2-f64a239c3c06.png)

### Additional information

I think that  there was A error

**Comment by MichaelHillcox** [comment]
Added to main list of launch issues #119 thanks for your help by reporting your issue, we're looking into it 👍
