### ISSUE TITLE
Skyfactory 3 and 2.5 dont launch after hitting the "play"-button

### ISSUE THREAD

**Issue by MoritzMiedler** [FTBTeam/FTB-App-Feedback#63]
### What Operating System

Windows 10

### App Version

202110071354-4bdfd15050-release

### UI Version

4bdfd15050

### Log Files

https://pste.ch/asexijoreq

### Debug Code

FTB-DBGGAPUKAKIWI

### Describe the bug

After hitting the play button, nothing happens. the button changes to "Loading..." but nothing else. after some time it changes back to play. 

### Steps to reproduce

start launcher
select skyfactory 3
click play

### Expected behaviour

button changes to "loading..." then changes back

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
