### ISSUE TITLE
[Bug]: Issue Joining Server After Update To Pack

### ISSUE THREAD

**Issue by avidgamer5918** [FTBTeam/FTB-App-Feedback#65]
### Modpack

FTB OceanBlock

### Modpack version

1.4.1

### Describe the bug

Every time I update the pack on both the ftb app and the gdlauncher I have to reinstall the instance in order for me to be able to log into my server for the pack. It just says failed to synchronize registry data from server closing connection.

### Steps to reproduce

Update pack 
try to join a server

### Expected behaviour

update instance and can log into server

### Screenshots

![2021-10-20_22 30 45](https://user-images.githubusercontent.com/34371965/138201059-834654ce-fbe0-4a66-8b2d-11c9712d5ddc.png)

**Comment by MichaelHillcox** [comment]
My assumption here is that it's not the mod loading, from my understanding, even if forge sees multiple versions, it'll attempt to sort them and load the newest version. I'd firstly request that @avidgamer5918 makes sure they are running the same version as the server is running.

I'm gunna close this for now but if this continues to be an issue after ensuring that the client and server are running the same version of the modpack then we can reopen the issue and look into it more
