### ISSUE TITLE
Update doesn't start

### ISSUE THREAD

**Issue by DrWilliamCraft** [FTBTeam/FTB-App-Feedback#66]
### What Operating System

Windows 11

### App Version

202110071354-4bdfd15050-release

### UI Version

4bdfd15050

### Debug Code

FTB-DBGIQECARUXED

### Describe the bug

FTB OceanBLock doesn't start to update 

### Steps to reproduce

1 Start the FTB App
2: Try to Update FTB OceanBlock to 1.4.1
3: I waited an Hour but it doesn't updated

![grafik](https://user-images.githubusercontent.com/85644421/138339228-4e28c666-4c77-4713-aa98-ead25f4e3225.png)

### Expected behaviour

That the Modpack Updates work 

### Additional information

My Way to Fix the Problem was to deinstall the modpack an Install the new Version (Beta)

**Comment by DrWilliamCraft** [comment]
Please ignore My Second Monitor that was an Acident :(

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
