### ISSUE TITLE
Fail To Prepare The Minecraft Launcher

### ISSUE THREAD

**Issue by BuzzLight3ar** [FTBTeam/FTB-App-Feedback#72]
### What Operating System

Windows 10

### App Version

202110071354-4bdfd15050-release

### UI Version

4bdfd15050

### Debug Code

FTB-DBGAGUCUDAPOW

### Describe the bug

So I install the FTB Mod pack and it comes up saying (Title of Repoty)

### Steps to reproduce

1. Install FTB Lanchure
2. install any mod pack 
3. Message shows 
4. unable to lanch game

### Expected behaviour

It Lanchues The MC Lanchure and open mod pack (works with forge)

### Screenshots

![image](https://user-images.githubusercontent.com/80061727/139541229-b2046fd5-2ec1-46df-acc0-6a94440d1648.png)

**Comment by Trogdayton** [comment]
Having the same issue. 
![image](https://user-images.githubusercontent.com/93630831/140021467-304aa802-32be-4ed5-9bd4-acb0275070e0.png)

**Comment by MichaelHillcox** [comment]
Please make sure you do not have minecraft or the minecraft launcher open in the background

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
