### ISSUE TITLE
Creating Environment issue when downloading a pack

### ISSUE THREAD

**Issue by ULSean** [FTBTeam/FTB-App-Feedback#73]
### What Operating System

Windows 10

### App Version

202110071354-4bdfd15050-release

### UI Version

4bdfd15050

### Log Files

I'm not sure what log files you need feel free to ask and I can provide.

### Debug Code

FTB-DBGLIKOFAWOGI

### Describe the bug

When Installing any modpack the installer will get stuck at Creating Environment under Initialise

### Steps to reproduce

1. Open FTB Launcher through Overwolf
2. Look for any pack
3. Start the install for any pack
4. The install wont go past Creating environment

### Expected behaviour

I hoped to install the game with no issues to happen. I had used the legacy launcher previously and only now wanted to play  Ocean Block

### Screenshots

![image](https://user-images.githubusercontent.com/57360055/139604811-cdfd9294-6b29-4042-b81a-4a39aba80637.png)

### Additional information

1. I have tried deleting both Overwolf and FTB with deleting the %localappdata% of Overwolf aswell. 
2. I have updated my java to the recommended version. 
3. I have tried restarting the install multiple times and sometimes it gets to install a vanilla launcher when I already have one.
4. When trying a different version of OceanBlock the same would happen.
5. I have also tried going to a beta version of the FTB launcher.

If there is anything else you need to help fix the issue feel free to ask!

Thank you in advance :)

**Comment by killer121135** [comment]
I have the same problem + when i got through that it got stuck as it shows on screenshot.

![Screenshot_13](https://user-images.githubusercontent.com/1576839/139624839-4d43bf2e-df0a-48e2-98eb-b6501f649c10.png)

**Comment by silvolivi** [comment]
having same problem (trying to download a modpack)

![immagine](https://user-images.githubusercontent.com/61496640/143563462-73ef34b7-241e-4d6e-9305-89b3ba5d4e30.png)

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
