### ISSUE TITLE
Stuck on Creating Environment 

### ISSUE THREAD

**Issue by ctw0050** [FTBTeam/FTB-App-Feedback#74]
### What Operating System

Windows 10

### App Version

202110071354-4bdfd15050-release

### UI Version

4bdfd15050

### Debug Code

FTB-DBGOSECUYAKUN

### Steps to reproduce

1. Open Overwolf
2. Launch FTB App
3. Locate Mod Pack
4. Click "Get"
5. Choose Version and click "Install"
6. Wait, stays at "Gather Data from API" and "Creating Environment" on the bottom

### Expected behaviour

Should complete install of Mod

### Screenshots

![Screenshot 2021-11-01 141922](https://user-images.githubusercontent.com/93549056/139728577-62a4fccb-8122-4021-97bd-acd0c018acb8.png)

**Comment by CoryNB** [comment]
ram specs limit options, it could be related to unmaxed ram to your build. or the ram mhz is below 1000 mhz.

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
