### ISSUE TITLE
new minecraft launcher

### ISSUE THREAD

**Issue by awolfrost** [FTBTeam/FTB-App-Feedback#77]
### What Operating System

Windows 10

### Debug Code

FTB-DBGJAJEFAFEGE

### Describe the bug

how do i migreat minecraft mods to the new launcher

### Steps to reproduce

idont know

### Expected behaviour

hopefully help with the new launcher

### Additional information

and i followed the video on making the seared smeltery and it doesnt work in ftb revalations

**Comment by awolfrost** [comment]
thank you very much

**Comment by MichaelHillcox** [comment]
Move mods from one mods folder to the new one, no clue what you're asking here but doesn't seem app related so: Closed
