### ISSUE TITLE
Mod version dropdown window doesn't have enough space to display the eternity of the mod version.

### ISSUE THREAD

**Issue by NJM1564** [FTBTeam/FTB-App-Feedback#78]
### What Operating System

Windows 10

### Debug Code

FTB-DBGCOZUQOXESU

### Describe the bug

Mod version dropdown window doesn't have enough space to display the eternity of the mod version.

### Steps to reproduce

1. Go to add more mods
2. Go to a mod. Example. Mystical Agradditions
3. Hit install
4. Open drop down menu under select options
5. Be frustrated that they all say MysticalAgradditions-... or MysticalAgradditions_1... 
With the ... meaning that the rest of the name is off the screen.

### Expected behaviour

The box being wide enough to read it all or wrapping the text around to the next line.

**Comment by MichaelHillcox** [comment]
Ignore the bot, I know of the issue, thanks for reporting it. It'll be sorted I'm the next version of the app

**Comment by MichaelHillcox** [comment]
Fixed in production :+1:
