### ISSUE TITLE
FTB App not starting

### ISSUE THREAD

**Issue by benasma8730** [FTBTeam/FTB-App-Feedback#80]
### What Operating System

Windows 10

### Debug Code

FTB-DBGIHAMOQUNIQ

### Describe the bug

The FTB App not launching

### Steps to reproduce

Going to Overwolf app trying to start the app get the screen thats saying somthing is wrong

### Expected behaviour

I expected that the app would start

### Screenshots

![image](https://user-images.githubusercontent.com/55389404/140639308-2e6d3b63-f292-4362-b759-9dbbdbd2b1c8.png)

**Comment by Raidobw2** [comment]
App log relayed by MadRat96 on the Discord, same issue:
https://pste.ch/ucabecataz

**Comment by Raidobw2** [comment]
What we tried, in order:
1. Deleting `%localappdata%\.ftba\._format.json` and starting the App.
2. Deleting `%localappdata%\.ftba\._format.json` and `%localappdata%\.ftba\bin\settings.json` and starting the App.
3. Deleting `%localappdata%\.ftba` and starting the App.

The user benasma8730 got the same error on each of those tries.

Additional info: They also uninstalled Overwolf and the FTB App, and reinstalled with the same result, before coming in the FTB Discord for our help.

**Comment by SkippyPanther** [comment]
Also having the same issue, tried all the above and the issue still exists

**Comment by blowsupalot** [comment]
Also having same issue. Is there a fix for this yet?

**Comment by MrGuffy** [comment]
@Raidobw2 :)

**Comment by benasma8730** [comment]
I think for me it got fixed. I didn't do anything by the way :) (trying to launch any modpack right now, will report back)

**Comment by benasma8730** [comment]
Everything seems to work fine now. Thanks for FTB Apps team for the support.
