### ISSUE TITLE
Minecraft not launching

### ISSUE THREAD

**Issue by Narkit** [FTBTeam/FTB-App-Feedback#84]
### What Operating System

Windows 10

### App Version

202111101147-418dcf2f3b-release

### UI Version

418dcf2f3b

### Log Files

https://pste.ch/uvemucuyiw

### Debug Code

FTB-DBGAJUDODIXOS

### Describe the bug

modpacks not launching

### Steps to reproduce

i just click play in the FTB app while having minecraft launcher open

### Expected behaviour

launching minecraft

**Comment by MichaelHillcox** [comment]
Added to main list of launch issues #119 thanks for your help by reporting your issue, we're looking into it :+1:
