### ISSUE TITLE
Launcher doesnt show any progress on downloading GT New Horizons

### ISSUE THREAD

**Issue by OldSoftwareCollection** [FTBTeam/FTB-App-Feedback#85]
### What Operating System

Windows 10

### App Version

202111101147-418dcf2f3b-release

### UI Version

418dcf2f3b

### Log Files

https://pste.ch/vutavetika

### Debug Code

FTB-DBGOQOPORAFUT

### Describe the bug

Launcher doesnt show any progress on downloading/installing GT New Horizons. No created folders for its instance, screen stays the same no matter how much time is passed

### Steps to reproduce

1)Launch FTB App
2)Click on "browse", check curseforge modpacks button, search for New Horizons.
3)Click on "get", select latest release, click install
4)Launcher shows the same screen for at least 20 minutes and doesnt show any progress about it. When i checked the folder with the instances, it didnt even created a folder for it, no matter when i checked the folder when the downloading only started or when i checked it after 20 minutes passed

### Expected behaviour

1)Launcher creating at least an empty folder for the new instance when the downloads started
2)Launcher showing any progress about what does its doing and estimately how much should user wait more for it to install the instance

### Screenshots

![image](https://user-images.githubusercontent.com/91433566/141655211-5f56b1a5-2ef1-46e0-b858-51adceacff8a.png)

**Comment by Omsk500** [comment]
3 of my friends have the same Problem. They did just like described, except with FTB Academy. The progress bar was stuck at for example 62,3% and didn`t move any further.

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
