### ISSUE TITLE
App does not open

### ISSUE THREAD

**Issue by WxvenYT** [FTBTeam/FTB-App-Feedback#86]
### What Operating System

Windows 10

### App Version

Unsure(maybe newest)

### UI Version

Unsure

### Debug Code

FTB-DBGTUKIPUWOHO

### Describe the bug

I cannot open the app, get an error saying it could be a one off bug every time, R3GEN on discord tried to help but could not resolve the issue

### Steps to reproduce

I am unsure

### Expected behaviour

Get an error message

### Screenshots

![Screenshot (3)](https://user-images.githubusercontent.com/94284468/141673527-c376ffc3-744c-4f84-99e2-406e345f640e.png)

**Comment by Shadowrs** [comment]
same

**Comment by MrGuffy** [comment]
Same.. :(

**Comment by ossman11** [comment]
This might be related to this issue #80

**Comment by CoryNB** [comment]
I get it after I leave the ftb launcher on too long with Minecraft in the background.

**Comment by MichaelHillcox** [comment]
Added to main list of launch issues #119 thanks for your help by reporting your issue, we're looking into it :+1:
