### ISSUE TITLE
Error failed to download Minecraft launcher

### ISSUE THREAD

**Issue by hiddenghost556** [FTBTeam/FTB-App-Feedback#87]
### What Operating System

Windows 10

### App Version

202111101147-418dcf2f3b-release

### UI Version

418dcf2f3b

### Debug Code

FTB-DBGAWOCURIRED 

### Describe the bug

when im trying to download ocean block mod pack when i click download it starts the download process and them im immediately says error faild to download minecraft launcher please report bug 

### Steps to reproduce

1. open the FTB app 
2. search for oceanblock 
3. click download 
4. choose 1.8.0 
5. download starts 
6. Error failed to download minecraft launcher 

### Expected behaviour

i expected to click download choose what version i wanted and for it to download the mod pack and install it 

### Screenshots

![bug minecraft](https://user-images.githubusercontent.com/94666656/142567250-d3c82eec-f3e3-4c30-892c-914782aacbf6.png)

**Comment by hiddenghost556** [comment]
![bug report](https://user-images.githubusercontent.com/94666656/142567640-e1247161-6224-40d0-8d12-44ebd8ef9b14.png)
i ran the program buti do not see any debug code to provide any help would be appreciated also will do what i can to help i love FTB thank you

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
