### ISSUE TITLE
FTB Oceanblock can't downgrade version nor uninstall in app 

### ISSUE THREAD

**Issue by mmaism** [FTBTeam/FTB-App-Feedback#88]
### What Operating System

Windows 10

### App Version

202111101147-418dcf2f3b-release

### UI Version

418dcf2f3b

### Debug Code

FTB-DBGEZUHARALUR

### Describe the bug

Downgrading from 1.8.0 is getting me stuck on "creating environment"

### Steps to reproduce

1. Update files to Oceanblock beta version 1.9.0
2. Downgrade to 1.8.0 (it showed me an error which i didnt print)
3. Downgrade to 1.7.0

### Expected behaviour

It should downgrade smoothly to 1.7.0

### Screenshots

<img width="959" alt="Screenshot_1" src="https://user-images.githubusercontent.com/94725794/142708957-1ecd999a-9ebb-47a1-98e3-149e578b42fd.png">

### Additional information

It's supposed to start downgrading by getting check marks on the steps but it stays stuck. I'm doing this since I created an oceanblock 1.8.0 server. Got "incomplete set of tags received from server" while my friends didn't. Realised I was on 1.9.0 beta client version. Downgraded to 1.8.0, got an error but it still downgraded (atleast shows i'm in 1.8.0 version). Still got the same error.

**Comment by CoryNB** [comment]
similar issue to removing mods

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
