### ISSUE TITLE
Linux + nVidia + prime-run + FTBA = black screen

### ISSUE THREAD

**Issue by JakeMoe** [FTBTeam/FTB-App-Feedback#89]
### What Operating System

Linux (Arch)

### App Version

202111051727-fc8797cf31-release

### UI Version

fc8797cf31

### Debug Code

FTB-DBGIYIKOLADUJ

### Describe the bug

App only shows black screen (no content) when using prime-run

### Steps to reproduce

Unpack app files to folder
Launch installer with "prime-run ~/FTBA/FTBApp"
Get greeted with black content window

### Expected behaviour

Content shows in window

### Screenshots

![without-prime-run](https://user-images.githubusercontent.com/2450407/142712685-2800900e-34f5-4406-83e8-655df7326731.jpeg)
![with-prime-run](https://user-images.githubusercontent.com/2450407/142712687-54ad74ae-5499-4b75-bf43-8482d66b947b.jpeg)

### Additional information

If I run without prime-run, the app works fine, but I'm stuck with my Intel iGPU in Minecraft.  If I run without prime-run and take a screenshot, then use that screenshot to guide my click, I can run with prime-run, click where my modpack icon is, and it launches Minecraft without issue and Minecraft tells me I'm using my nVidia GPU.

From what I understand, it's an Electron issue; I have the same problem with  Discord if I use prime-run (which I don't, normally, as I don't care if it uses the Intel GPU).  I used to have the same problem with VS Code, which I believe is Electron-based as well, but it seems to work now, so perhaps they found a way?

FWIW, I'm running on Arch Linux using FVWM as window manager on a Dell Latitude 5520.

**Comment by MichaelHillcox** [comment]
What's prime-run (the td;lr plx)  and did you run the debug tool when having the black screen as the logs show you getting into Minecraft / I can see it starting with other errors.

**Comment by JakeMoe** [comment]
"prime-run" is a tool in Linux on nVidia hybrid graphics systems used to force-start applications using the discrete nVidia GPU rather than the integrated Intel one.  It's nothing more than a shell script that sets a few nVidia-specific environment variables and then launches whatever you put as the argument.  Here's the whole script:

```
#!/bin/bash
__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia "$@"
```

If needed / interested, a little more info can be found here: [https://wiki.archlinux.org/title/PRIME](https://wiki.archlinux.org/title/PRIME).  That's the Arch Linux page for it, but the concept (and the tool) applies to other distributions.

As for the debug tool, I'm not sure; it just said to run it, I don't remember if I ran it while I was having the problem  I've re-run it again while the screen is blank (and I'm running the pack), the code is FTB-DBGFOKOKOPAWU.  But like I said, when I launch it using prime-run, while the screen is black, I can click the location where DireWolf20 is in my Recently Played list (I can see the cursor change from a pointer to a finger as well), and it starts the Minecraft launcher fine, and that starts the DireWolf20 pack fine as well, so I'd expect the logs to say I'm getting into Minecraft.  :-)  Everything else works, I just can't see anything in the FTB Launcher (as per the second screenshot above).

**Comment by MichaelHillcox** [comment]
Added to main list of launch issues #119 thanks for your help by reporting your issue, we're looking into it :+1:
