### ISSUE TITLE
It doesnt let me sign up to the minetoghether thing because when they say that they are going to send me an email,it doesnt matter how many times i try to re sent,it doesnt get sent

### ISSUE THREAD

**Issue by SirCuenca** [FTBTeam/FTB-App-Feedback#90]
### What Operating System

MacOS (Latest)

### Debug Code

its doesnt let me

### Describe the bug

It doesnt let me sign up to the minetoghether thing because when they say that they are going to send me an email,it doesnt matter how many times i try to re sent,it doesnt get sent,but the way,my gmail is alelucenodisney@gmail.com

### Steps to reproduce

integrations,then the minetoghether botton,try to login and try to verify your email,then go to your email and see nothing

### Expected behaviour

to send me the email

### Additional information

HELP

**Comment by MichaelHillcox** [comment]
If you do not intent on using MineTogether, you do not need to sign into it. I'd ask you to contact the CreeperHost team about this issue as we do not have the ability to handle any issues that may come from CreeperHost systems.
