### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by FestiveCookie75** [FTBTeam/FTB-App-Feedback#93]
### What Operating System

Windows 10

### Debug Code

FTB-DBGLOKABAHOHE

### Describe the bug

FTB wont open because 3 mods need a newer version of forge and I just updated the mod pack

### Steps to reproduce

Launching the new update for FTB minecraft

### Expected behaviour

A way to launch the game

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
