### ISSUE TITLE
I can't join my singleplayer word.

### ISSUE THREAD

**Issue by Lawiet86** [FTBTeam/FTB-App-Feedback#94]
### What Operating System

Windows 10

### Debug Code

FTB-DBGASABINANAD

### Describe the bug

I loaded up Stoneblock 2 and i cant't find my singleplayer word in the menu.

### Steps to reproduce

I don't know. I didn't do anything, nor deleted it. I just played on it yesterday.

### Expected behaviour

I expected to my word to be in the menu so i can click on it and play on it.

### Screenshots

https://imgur.com/a/mQTXVeR

**Comment by CoryNB** [comment]
I belive it may have had a change to mods, updates and additions break it. delete old world and create new.

**Comment by MichaelHillcox** [comment]
Added to the main list of startup & install issues. We're actively looking into and trying to resolve all of these issues. Thank you for reporting your issue. You can keep track of any changes here #120 :+1:
