### ISSUE TITLE
minetogether

### ISSUE THREAD

**Issue by inferno1102** [FTBTeam/FTB-App-Feedback#97]
### What Operating System

Windows 10

### App Version

202111101147-418dcf2f3b-release

### UI Version

418dcf2f3b

### Debug Code

FTB-DBGICAQEXUWEG

### Describe the bug

minetogether not connecting

### Steps to reproduce

1. launch oceanblock
2. check chat in top right
3. says disconnected button left

### Expected behaviour

it to say verified or connected and chat to pop up

### Screenshots

![image](https://user-images.githubusercontent.com/95211263/143831367-6fb9f2d4-1a7d-4c64-ad76-4900b028abce.png)

### Additional information

I think i need to run the minecraft launcher in administrative mode, however this option doesnt seem available to me, and when i try to change the launcher file itself then the FTB launcher wont load the mod pack at all. I cannot seem to find a way to launch the minecraft launcher the FTB app launches in administrative mode. No, launching FTB app in admin mode doesnt help.

**Comment by MichaelHillcox** [comment]
Please contact minetogether / CreeperHost support, this isn't an app issue
