### ISSUE TITLE
FTB Oceanblock 1.9.0 don`t works

### ISSUE THREAD

**Issue by TheCorpio** [FTBTeam/FTB-App-Feedback#99]
### What Operating System

Windows 10

### App Version

FTB Oceanblock

### UI Version

1.9.0

### Log Files

[crash-2021-11-30_21.55.46-fml.txt](https://github.com/FTBTeam/FTB-App-Feedback/files/7628178/crash-2021-11-30_21.55.46-fml.txt)

### Debug Code

FTB-DBGINEKEVUGIZ

### Describe the bug

The game does not start

### Steps to reproduce

After the last game, the game stopped running

### Expected behaviour

To start the game

### Screenshots

![image](https://user-images.githubusercontent.com/95311270/144111837-93638a4c-49a3-403c-a0e0-8a32530da40a.png)

**Comment by TheCorpio** [comment]
This problem occurs only with my saving.

**Comment by TheCorpio** [comment]
The problem was solved by removing the mod Optifine

**Comment by TheCorpio** [comment]
Deleted Optifine the game started. The next day, the game did not start again. The game starts if there is no my world. Also reinstalling the client doesn't help either. Downgrading the mod version didn't help. Please tell me what could be. I really want to play.

**Comment by CoryNB** [comment]
I believe it was corrupted. ftb may need to be reinstalled, but with curse forge as well. windows 11 works with ftb now. the ram mhz needed to play have to be met above 1000 mhz ram speed. the system ram must be above 10/16 to 20+Gb of ram. can you install the version of those mods in the profile again?

**Comment by TheCorpio** [comment]
The problem is that I reinstalled the mod and the entire build. It was allocated 6 GB and worked well. If you delete my world from the save folder, it starts fine, and you can continue playing, but i don't want to lose my save.



> I believe it was corrupted. ftb may need to be reinstalled, but with curse forge as well. windows 11 works with ftb now. the ram mhz needed to play have to be met above 1000 mhz ram speed. the system ram must be above 10/16 to 20+Gb of ram. can you install the version of those mods in the profile again?

**Comment by MichaelHillcox** [comment]
Please report this issue to the author of Titanium. If they say that it's not their issue then we can reopen this issue and look into it more :+1:
